### ISSUE TITLE
「口コミ」と「レビュー」で表記揺れがある

### ISSUE THREAD

**Issue by masibw** [harukitosa/student-salary#6]
topページでは「レビュー」だが，メニューバーでは「口コミ」になっている
![スクリーンショット 2021-10-17 21 50 04](https://user-images.githubusercontent.com/43804414/137627893-55beec51-0b45-4bc0-afa3-c469d486e623.jpg)

![スクリーンショット 2021-10-17 21 50 43](https://user-images.githubusercontent.com/43804414/137627902-5fbc86a6-baa2-4e50-84d3-8e733e0dd52a.jpg)

**Comment by harukitosa** [comment]
ありがとうございます🙇‍♂️
あとで(諸説あり) 修正します！
